apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: neting
  name: neting
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: neting
  type: NodePort
status:
  loadBalancer: {}

